"""
ACMGS Phase 6: Carbon-Aware Decision Logic

WHY THIS EXISTS:
The carbon intensity of the electrical grid changes throughout the day based on 
what energy sources are active (solar, wind, coal, gas). This scheduler acts as 
the "brain" of the system, dynamically selecting the optimal manufacturing 
configuration based on real-time grid carbon intensity.

CONCEPTUAL FRAMEWORK:
- When grid is clean (LOW carbon) → Maximize production (high yield/quality)
- When grid is dirty (HIGH carbon) → Minimize energy/carbon (conservation mode)
- When grid is moderate (MEDIUM) → Balance all objectives (efficiency mode)

DECISION ZONES:
- LOW zone (≤150 gCO2/kWh): Clean grid → Run at full performance
- MEDIUM zone (150-400 gCO2/kWh): Mixed grid → Balanced optimization  
- HIGH zone (≥400 gCO2/kWh): Dirty grid → Energy conservation

HOW IT WORKS:
1. Load Pareto-optimal solutions from Phase 5 (pareto_solutions.csv)
2. Classify current carbon intensity into a zone (HIGH/MEDIUM/LOW)
3. Apply zone-specific selection logic to pick best configuration
4. Return complete recommendation with zone, carbon level, and schedule

USAGE:
    python -m src.carbon_scheduler.scheduler
"""

import os
import pandas as pd
from typing import Dict
from config.settings import (
    SIMULATED_DIR,
    CARBON_HIGH_THRESHOLD,
    CARBON_LOW_THRESHOLD
)
from src.utils.logger import get_logger

# Initialize logger for this module
logger = get_logger("carbon_scheduler.scheduler")


def load_pareto_solutions() -> pd.DataFrame:
    """
    Load Pareto-optimal manufacturing configurations from Phase 5.
    
    This function reads the pareto_solutions.csv file generated by the 
    optimization engine (Phase 5). Each row represents a manufacturing 
    configuration that is Pareto-optimal - meaning you cannot improve one 
    objective without degrading another.
    
    Returns
    -------
    pd.DataFrame
        DataFrame with columns:
        Process Parameters:
            - temperature: Manufacturing temperature setting
            - pressure: Manufacturing pressure setting
            - speed: Production line speed
            - feed_rate: Material feed rate
            - humidity: Environmental humidity level
        Material Parameters:
            - material_density: Density of input material
            - material_hardness: Hardness of input material
            - material_grade: Grade/quality tier of material
        Optimization Context:
            - carbon_intensity: Grid carbon level this was optimized for
        Predicted Outcomes:
            - pred_yield: Predicted production yield (%)
            - pred_quality: Predicted product quality score
            - pred_energy: Predicted energy consumption (kWh)
            - pred_carbon: Predicted carbon emissions (kgCO2)
    
    Raises
    ------
    FileNotFoundError
        If pareto_solutions.csv does not exist (Phase 5 must be run first)
    
    Notes
    -----
    The Pareto frontier represents the best possible trade-offs between:
    - Maximizing yield and quality (production goals)
    - Minimizing energy and carbon (sustainability goals)
    """
    pareto_path = os.path.join(SIMULATED_DIR, "pareto_solutions.csv")
    
    # Check if Phase 5 output exists
    if not os.path.exists(pareto_path):
        error_msg = (
            f"Pareto solutions file not found at {pareto_path}. "
            f"Phase 5 (optimization) must be run first to generate this file."
        )
        logger.error(error_msg)
        raise FileNotFoundError(error_msg)
    
    logger.info(f"Loading Pareto-optimal solutions from: {pareto_path}")
    df = pd.read_csv(pareto_path)
    logger.info(f"Loaded {len(df)} Pareto-optimal manufacturing configurations")
    
    return df


def classify_carbon_zone(carbon_intensity: float) -> str:
    """
    Classify current carbon intensity into a decision zone.
    
    The electrical grid's carbon intensity varies based on the energy mix:
    - Clean grid (solar, wind, hydro): Low carbon intensity
    - Mixed grid (gas + renewables): Medium carbon intensity  
    - Dirty grid (coal, peaker plants): High carbon intensity
    
    This function maps continuous carbon intensity values to discrete zones
    that guide manufacturing strategy.
    
    Parameters
    ----------
    carbon_intensity : float
        Current grid carbon intensity in gCO2/kWh
        Typical range: 0-1000+ gCO2/kWh
        Examples:
            - 50 gCO2/kWh: Very clean (100% renewable)
            - 250 gCO2/kWh: Moderate (natural gas dominated)
            - 500 gCO2/kWh: High (coal dominated)
    
    Returns
    -------
    str
        One of three zones: "HIGH", "MEDIUM", or "LOW"
    
    Decision Thresholds
    -------------------
    HIGH zone (>= 400 gCO2/kWh):
        - Grid is dirty (likely coal or heavy fossil fuel use)
        - Strategy: Minimize energy consumption and carbon emissions
        - Action: Delay energy-intensive operations
        
    LOW zone (<= 150 gCO2/kWh):
        - Grid is clean (likely renewable energy dominance)
        - Strategy: Maximize production output and quality
        - Action: Run at full capacity, bank production
        
    MEDIUM zone (150-400 gCO2/kWh):
        - Grid has mixed energy sources
        - Strategy: Balance production goals with sustainability
        - Action: Optimize for efficiency (output per unit energy)
    
    Notes
    -----
    Thresholds are imported from config.settings:
    - CARBON_HIGH_THRESHOLD = 400 gCO2/kWh
    - CARBON_LOW_THRESHOLD = 150 gCO2/kWh
    """
    if carbon_intensity >= CARBON_HIGH_THRESHOLD:
        zone = "HIGH"
    elif carbon_intensity <= CARBON_LOW_THRESHOLD:
        zone = "LOW"
    else:
        zone = "MEDIUM"
    
    logger.debug(
        f"Carbon intensity {carbon_intensity:.1f} gCO2/kWh "
        f"classified as {zone} zone"
    )
    return zone


def select_best_schedule(df_pareto: pd.DataFrame, zone: str) -> Dict:
    """
    Select optimal manufacturing configuration for the given carbon zone.
    
    This function implements zone-specific decision logic to pick the best
    manufacturing schedule from the Pareto-optimal frontier. Each zone has
    a different optimization strategy based on grid conditions.
    
    Parameters
    ----------
    df_pareto : pd.DataFrame
        Pareto-optimal solutions from load_pareto_solutions()
        Must contain columns: pred_yield, pred_quality, pred_energy, pred_carbon
    zone : str
        Carbon zone: "HIGH", "MEDIUM", or "LOW"
        Determines which selection strategy to apply
    
    Returns
    -------
    dict
        Best manufacturing configuration as a dictionary containing all columns
        from the selected row in pareto_solutions.csv
    
    Selection Strategies
    --------------------
    HIGH ZONE (Dirty Grid):
        Objective: Minimize environmental impact
        Formula: score = pred_energy + pred_carbon (minimize)
        Logic: During high-carbon periods, prioritize saving energy and 
               reducing emissions. Accept lower production to wait for 
               cleaner grid conditions.
        Example scores:
            Config A: energy=100, carbon=50 → score=150
            Config B: energy=80, carbon=40 → score=120 ✓ BEST
            
    LOW ZONE (Clean Grid):
        Objective: Maximize production output
        Formula: score = pred_yield + pred_quality (maximize)
        Logic: During clean-grid periods, run at maximum capacity to 
               capitalize on renewable energy availability. Bank production
               for later high-carbon periods.
        Example scores:
            Config A: yield=85, quality=90 → score=175
            Config B: yield=95, quality=92 → score=187 ✓ BEST
            
    MEDIUM ZONE (Mixed Grid):
        Objective: Balance all competing objectives
        Formula: score = pred_yield + pred_quality - pred_energy - pred_carbon
        Logic: Balance production goals against sustainability. Optimize for
               efficiency - getting maximum output per unit energy consumed.
        Example scores:
            Config A: 85+90-100-50 = 25
            Config B: 90+88-95-45 = 38 ✓ BEST
            Config C: 95+92-120-60 = 7
    
    Notes
    -----
    The function creates a temporary 'score' column for ranking, then removes
    it before returning the selected configuration. The original DataFrame
    is not modified (uses .copy()).
    """
    # Create working copy to avoid modifying original
    df = df_pareto.copy()
    
    if zone == "HIGH":
        # HIGH CARBON: Minimize energy and carbon (conservation mode)
        df["score"] = df["pred_energy"] + df["pred_carbon"]
        best_idx = df["score"].idxmin()  # Find minimum score
        logger.info(
            f"HIGH carbon zone → Selecting energy-saving configuration "
            f"(conservation mode, score={df.loc[best_idx, 'score']:.2f})"
        )
        
    elif zone == "LOW":
        # LOW CARBON: Maximize yield and quality (full performance mode)
        df["score"] = df["pred_yield"] + df["pred_quality"]
        best_idx = df["score"].idxmax()  # Find maximum score
        logger.info(
            f"LOW carbon zone → Selecting high-performance configuration "
            f"(full production mode, score={df.loc[best_idx, 'score']:.2f})"
        )
        
    else:  # MEDIUM
        # MEDIUM CARBON: Balanced optimization (efficiency mode)
        # Normalize each objective to [0,1] so they contribute equally
        for col in ["pred_yield", "pred_quality", "pred_energy", "pred_carbon"]:
            col_min, col_max = df[col].min(), df[col].max()
            col_range = col_max - col_min if col_max > col_min else 1.0
            df[f"_norm_{col}"] = (df[col] - col_min) / col_range
        # Reward high yield/quality, penalize high energy/carbon
        df["score"] = (
            df["_norm_pred_yield"] + df["_norm_pred_quality"] -
            df["_norm_pred_energy"] - df["_norm_pred_carbon"]
        )
        # Clean up temporary normalization columns
        df.drop(columns=[c for c in df.columns if c.startswith("_norm_")], inplace=True)
        best_idx = df["score"].idxmax()  # Find maximum balanced score
        logger.info(
            f"MEDIUM carbon zone → Selecting balanced configuration "
            f"(efficiency mode, score={df.loc[best_idx, 'score']:.2f})"
        )
    
    # Extract best configuration as dictionary
    best_schedule = df.loc[best_idx].to_dict()
    
    # Remove temporary score column
    if "score" in best_schedule:
        del best_schedule["score"]
    
    return best_schedule


def get_recommendation(carbon_intensity: float) -> Dict:
    """
    Orchestrate the full carbon-aware scheduling recommendation pipeline.
    
    This is the main entry point for getting a manufacturing recommendation.
    It coordinates all the steps: loading data, classifying the carbon zone,
    selecting the optimal schedule, and packaging the full recommendation.
    
    Parameters
    ----------
    carbon_intensity : float
        Current grid carbon intensity in gCO2/kWh
        This would typically come from a real-time grid API in production
    
    Returns
    -------
    dict
        Complete recommendation with three keys:
        - zone : str
            The classified carbon zone ("HIGH", "MEDIUM", or "LOW")
        - carbon_intensity : float
            The input carbon intensity value (for reference)
        - recommended_schedule : dict
            The optimal manufacturing configuration containing:
                - All process parameters (temperature, pressure, etc.)
                - All material parameters (density, hardness, grade)
                - All predicted outcomes (yield, quality, energy, carbon)
    
    Workflow
    --------
    1. Load Pareto-optimal solutions from Phase 5 output
    2. Classify current carbon intensity into a zone
    3. Select best schedule using zone-specific logic
    4. Package complete recommendation with all metadata
    5. Log summary of key metrics for audit trail
    
    Example
    -------
    >>> recommendation = get_recommendation(carbon_intensity=250.0)
    >>> print(recommendation["zone"])
    'MEDIUM'
    >>> print(recommendation["recommended_schedule"]["pred_yield"])
    88.5
    
    Notes
    -----
    In production, this function would be called periodically (e.g., every
    15 minutes) with real-time carbon intensity data from grid APIs or
    forecasting models. The recommendation would then be sent to the
    manufacturing control system for implementation.
    """
    logger.info("=" * 80)
    logger.info(
        f"Generating carbon-aware recommendation for "
        f"carbon_intensity = {carbon_intensity:.1f} gCO2/kWh"
    )
    logger.info("=" * 80)
    
    # Step 1: Load Pareto solutions
    df_pareto = load_pareto_solutions()
    
    # Step 2: Classify carbon zone
    zone = classify_carbon_zone(carbon_intensity)
    
    # Step 3: Select best schedule for this zone
    best_schedule = select_best_schedule(df_pareto, zone)
    
    # Step 4: Build complete recommendation
    recommendation = {
        "zone": zone,
        "carbon_intensity": carbon_intensity,
        "recommended_schedule": best_schedule
    }
    
    # Step 5: Log summary with key metrics
    logger.info(
        f"Recommendation complete:\n"
        f"   Zone: {zone}\n"
        f"   Carbon Intensity: {carbon_intensity:.1f} gCO2/kWh\n"
        f"   Predicted Yield: {best_schedule['pred_yield']:.2f}\n"
        f"   Predicted Quality: {best_schedule['pred_quality']:.2f}\n"
        f"   Predicted Energy: {best_schedule['pred_energy']:.2f} kWh\n"
        f"   Predicted Carbon: {best_schedule['pred_carbon']:.2f} kgCO2"
    )
    
    return recommendation


def run_scheduler_pipeline():
    """
    Test the carbon-aware scheduler with representative scenarios.
    
    This function demonstrates the scheduler's behavior across three distinct
    carbon intensity scenarios that reflect real-world grid conditions:
    
    Test Scenarios
    --------------
    1. Clean Grid (50 gCO2/kWh) - LOW zone
       - Typical of midday with high solar generation
       - Or regions with high renewable penetration
       - Expected: Maximum performance configuration
       
    2. Moderate Grid (250 gCO2/kWh) - MEDIUM zone
       - Typical of natural gas dominated periods
       - Or mixed fossil fuel + renewable periods
       - Expected: Balanced efficiency configuration
       
    3. Dirty Grid (500 gCO2/kWh) - HIGH zone
       - Typical of peak demand with coal generation
       - Or evening periods with no solar
       - Expected: Energy conservation configuration
    
    Outputs
    -------
    Logs:
        Detailed execution logs showing decision process for each scenario
    CSV File:
        data/simulated/carbon_schedule_demo.csv containing:
        - zone: Carbon zone classification
        - carbon_intensity: Input carbon value
        - schedule_*: All parameters and predictions (flattened)
    
    Notes
    -----
    In production, this pipeline would run continuously with real-time data.
    This test version demonstrates the decision logic and validates that all
    components work correctly across the full range of carbon intensities.
    """
    logger.info("=" * 80)
    logger.info("STARTING CARBON-AWARE SCHEDULER PIPELINE (PHASE 6)")
    logger.info("=" * 80)
    logger.info("")
    logger.info("This pipeline tests the scheduler with 3 representative scenarios:")
    logger.info("  1. Clean grid (LOW carbon) - maximize performance")
    logger.info("  2. Moderate grid (MEDIUM carbon) - balance objectives")
    logger.info("  3. Dirty grid (HIGH carbon) - minimize energy/carbon")
    logger.info("")
    
    # Define test scenarios
    test_cases = [
        {
            "label": "Clean Grid (LOW carbon)",
            "carbon_intensity": 50.0,
            "description": "High renewable energy (solar/wind)"
        },
        {
            "label": "Moderate Grid (MEDIUM carbon)",
            "carbon_intensity": 250.0,
            "description": "Mixed natural gas and renewables"
        },
        {
            "label": "Dirty Grid (HIGH carbon)",
            "carbon_intensity": 500.0,
            "description": "Coal-dominated or peak demand"
        }
    ]
    
    recommendations = []
    
    # Execute each test case
    for i, test in enumerate(test_cases, 1):
        logger.info("=" * 80)
        logger.info(f"TEST CASE {i}/3: {test['label']}")
        logger.info(f"   Description: {test['description']}")
        logger.info(f"   Carbon Intensity: {test['carbon_intensity']:.1f} gCO2/kWh")
        logger.info("=" * 80)
        
        try:
            recommendation = get_recommendation(test["carbon_intensity"])
            recommendations.append(recommendation)
            logger.info("")
            
        except Exception as e:
            logger.error(f"Test case {i} failed: {e}")
            raise
    
    # Save results to CSV
    logger.info("=" * 80)
    logger.info("SAVING RECOMMENDATIONS TO CSV")
    logger.info("=" * 80)
    
    # Flatten recommendations for CSV export
    rows = []
    for rec in recommendations:
        row = {
            "zone": rec["zone"],
            "carbon_intensity": rec["carbon_intensity"]
        }
        # Flatten the recommended_schedule dict with 'schedule_' prefix
        for key, value in rec["recommended_schedule"].items():
            row[f"schedule_{key}"] = value
        rows.append(row)
    
    df_output = pd.DataFrame(rows)
    output_path = os.path.join(SIMULATED_DIR, "carbon_schedule_demo.csv")
    df_output.to_csv(output_path, index=False)
    
    logger.info(f"Saved {len(rows)} recommendations to: {output_path}")
    logger.info(f"   Columns: {len(df_output.columns)}")
    logger.info(f"   File size: {os.path.getsize(output_path)} bytes")
    logger.info("")
    
    # Final summary
    logger.info("=" * 80)
    logger.info("PHASE 6 COMPLETE: CARBON-AWARE SCHEDULER PIPELINE SUCCESSFUL")
    logger.info("=" * 80)
    logger.info("")
    logger.info("Summary of Recommendations:")
    for i, rec in enumerate(recommendations, 1):
        sched = rec["recommended_schedule"]
        logger.info(
            f"  {i}. {rec['zone']} zone ({rec['carbon_intensity']:.0f} gCO2/kWh): "
            f"Yield={sched['pred_yield']:.1f}, "
            f"Quality={sched['pred_quality']:.1f}, "
            f"Energy={sched['pred_energy']:.1f}, "
            f"Carbon={sched['pred_carbon']:.1f}"
        )
    logger.info("")
    logger.info("Next steps:")
    logger.info("  - Review carbon_schedule_demo.csv for detailed configurations")
    logger.info("  - Integrate with real-time carbon intensity APIs (Phase 7+)")
    logger.info("  - Connect to manufacturing control systems for execution")
    logger.info("=" * 80)


if __name__ == "__main__":
    run_scheduler_pipeline()
